### ISSUE TITLE
Update Restify dependencies

### ISSUE THREAD

**Issue by melloc** [joyent/kang#7]
Kang currently pulls in `restify@4.1.1` and `restify-clients@1.1.1`, which in turn pull in `dtrace-provider@0.6.0`. I'd like to use Kang with node v4, which requires at least `dtrace-provider@0.7.0`. Updating to `restify@4.3.2` and `restify-clients@1.5.2` will pull in `dtrace-provider@~0.8.0`.

**Comment by davepacheco** [comment]
This sounds great.  My questions are:

- Are there any worrying changes in the change log for restify or restify-clients?  I'm hoping not because they're not major bumps, but it would be worth reviewing.
- Does the new stuff still work with Node 0.10?  (Some kang consumers are still on 0.10.)

**Comment by melloc** [comment]
> Are there any worrying changes in the change log for restify or restify-clients? I'm hoping not because they're not major bumps, but it would be worth reviewing.

No, these bumps are within the same major range, and don't introduce any backwards-incompatible changes. The `restify@4.3.0` release did introduce the ability to disable domains with the `handleUncaughtExceptions: false` option, but I haven't touched that,. since I don't know whether anything's relying on it through Kang today.

> Does the new stuff still work with Node 0.10? (Some kang consumers are still on 0.10.)

Yes. I've been using the `restify@4.3.0` versions in NAPI and FWAPI, and they're still fine. I've also been using `restify-clients@1.5.x` with node v0.10 in several places.

**Comment by trentm** [comment]
Resolved by https://github.com/joyent/kang/pull/10
THis is published as kang@1.3.0 now.
